name: Austin Spurs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#10214a'
    - '#949494'
    - '#464646'
    - '#b6bbc7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
